### ISSUE TITLE
Live coding broken on reload with cxf extension enabled

### ISSUE THREAD

**Issue by mauro-antonaci** [quarkiverse/quarkus-cxf#94] opened 2021-01-08 14:07 UTC
In development mode, with live coding enabled, when I change something in source code and call any resource, server get broken with this error:

`
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: Found 11 deployment problems: 
[1] Unsatisfied dependency for type java.lang.String and qualifiers [@Default]
	- java member: io.quarkiverse.cxf.CXFClientInfo#<init>()
	- declared on CLASS bean [types=[io.quarkiverse.cxf.CXFClientInfo, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkiverse.cxf.CXFClientInfo]
	The following beans match by type, but none have matching qualifiers:
		- Bean [class=java.lang.String, qualifiers=[@ConfigProperty, @Any]]
[2] Unsatisfied dependency for type java.lang.String and qualifiers [@Default]
	- java member: io.quarkiverse.cxf.CXFClientInfo#<init>()
	- declared on CLASS bean [types=[io.quarkiverse.cxf.CXFClientInfo, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkiverse.cxf.CXFClientInfo]
	The following beans match by type, but none have matching qualifiers:
		- Bean [class=java.lang.String, qualifiers=[@ConfigProperty, @Any]]
[3] Unsatisfied dependency for type java.lang.String and qualifiers [@Default]
	- java member: io.quarkiverse.cxf.CXFClientInfo#<init>()
	- declared on CLASS bean [types=[io.quarkiverse.cxf.CXFClientInfo, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkiverse.cxf.CXFClientInfo]
	The following beans match by type, but none have matching qualifiers:
		- Bean [class=java.lang.String, qualifiers=[@ConfigProperty, @Any]]
[4] Unsatisfied dependency for type java.lang.String and qualifiers [@Default]
	- java member: io.quarkiverse.cxf.CXFClientInfo#<init>()
	- declared on CLASS bean [types=[io.quarkiverse.cxf.CXFClientInfo, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkiverse.cxf.CXFClientInfo]
	The following beans match by type, but none have matching qualifiers:
		- Bean [class=java.lang.String, qualifiers=[@ConfigProperty, @Any]]
[5] Unsatisfied dependency for type java.lang.String and qualifiers [@Default]
	- java member: io.quarkiverse.cxf.CXFClientInfo#<init>()
	- declared on CLASS bean [types=[io.quarkiverse.cxf.CXFClientInfo, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkiverse.cxf.CXFClientInfo]
	The following beans match by type, but none have matching qualifiers:
		- Bean [class=java.lang.String, qualifiers=[@ConfigProperty, @Any]]
[6] Unsatisfied dependency for type java.lang.String and qualifiers [@Default]
	- java member: io.quarkiverse.cxf.CXFClientInfo#<init>()
	- declared on CLASS bean [types=[io.quarkiverse.cxf.CXFClientInfo, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkiverse.cxf.CXFClientInfo]
	The following beans match by type, but none have matching qualifiers:
		- Bean [class=java.lang.String, qualifiers=[@ConfigProperty, @Any]]
[7] Unsatisfied dependency for type java.lang.String and qualifiers [@Default]
	- java member: io.quarkiverse.cxf.CXFClientInfo#<init>()
	- declared on CLASS bean [types=[io.quarkiverse.cxf.CXFClientInfo, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkiverse.cxf.CXFClientInfo]
	The following beans match by type, but none have matching qualifiers:
		- Bean [class=java.lang.String, qualifiers=[@ConfigProperty, @Any]]
[8] Unsatisfied dependency for type java.lang.String and qualifiers [@Default]
	- java member: io.quarkiverse.cxf.CXFClientInfo#<init>()
	- declared on CLASS bean [types=[io.quarkiverse.cxf.CXFClientInfo, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkiverse.cxf.CXFClientInfo]
	The following beans match by type, but none have matching qualifiers:
		- Bean [class=java.lang.String, qualifiers=[@ConfigProperty, @Any]]
[9] Unsatisfied dependency for type java.lang.String and qualifiers [@Default]
	- java member: io.quarkiverse.cxf.CXFClientInfo#<init>()
	- declared on CLASS bean [types=[io.quarkiverse.cxf.CXFClientInfo, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkiverse.cxf.CXFClientInfo]
	The following beans match by type, but none have matching qualifiers:
		- Bean [class=java.lang.String, qualifiers=[@ConfigProperty, @Any]]
[10] Unsatisfied dependency for type java.lang.String and qualifiers [@Default]
	- java member: io.quarkiverse.cxf.CXFClientInfo#<init>()
	- declared on CLASS bean [types=[io.quarkiverse.cxf.CXFClientInfo, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkiverse.cxf.CXFClientInfo]
	The following beans match by type, but none have matching qualifiers:
		- Bean [class=java.lang.String, qualifiers=[@ConfigProperty, @Any]]
[11] Unsatisfied dependency for type java.util.List<java.lang.String> and qualifiers [@Default]
	- java member: io.quarkiverse.cxf.CXFClientInfo#<init>()
	- declared on CLASS bean [types=[io.quarkiverse.cxf.CXFClientInfo, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkiverse.cxf.CXFClientInfo]
	The following beans match by type, but none have matching qualifiers:
		- Bean [class=java.util.List, qualifiers=[@ConfigProperty, @Any]]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1029)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:241)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:127)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:411)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:972)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
(....)`

So you need to manually restart the server with mvn quarkus:dev

(Can reproduce the error on quarkus 1.10.5.Final, OpenJDK 11 + quarkiverse/cxf v. 0.2 and v.0.3)

**Comment by wh81752** [comment] 2021-01-12 09:11
Facing exactly the same problem: 
* CXF 3.3.9
* $ java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment GraalVM CE 20.2.0 (build 11.0.8+10-jvmci-20.2-b03)
OpenJDK 64-Bit Server VM GraalVM CE 20.2.0 (build 11.0.8+10-jvmci-20.2-b03, mixed mode, sharing)
* Quarkus 1.10.3.FINAL
* quarkiverse/cxf v0.3

**Comment by dufoli** [comment] 2021-01-12 10:18
strange bug. I open an issue on quarkus to understand the issue.

**Comment by wh81752** [comment] 2021-01-18 13:03
Are there any news regarding this issue? Cause it's rather annoying to recompile / restart on any changes :-(

**Comment by ggam** [comment] 2021-01-26 12:28
I'm also facing this issue.

**Comment by wh81752** [comment] 2021-01-28 10:23
After updating to latest master-SNAPSHOT ([1b0fd1c](https://github.com/quarkiverse/quarkus-cxf/commit/1b0fd1c6c06d05165e53e36430d5b556952fe678)) the problem is **partially** solved:

```
@WebService(endpointInterface = "org.acme.cxf.FruitWebService")
public class FruitWebServiceImpl implements FruitWebService {
    private static final Logger logger = Logger.getLogger(FruitWebServiceImpl.class);

    @Override
    // @RolesAllowed("USER")                         // (B)
    public List<String> list() {
        logger.debug("incoming request..");     // (A)
        return Arrays.asList();
    }
 ..
}
```

Changes like (A) are working fine now, i.e. hot deployment works like a charm. 

Change (B) does not work, I'm facing again the problem of this issue. 

Btw: `@RolesAllowed` appears to work as well after this update.

**Comment by ambition-consulting** [comment] 2021-02-08 21:29
Same problem.

**Comment by dufoli** [comment] 2021-02-09 06:54
can you try branch issue94 ?

**Comment by dufoli** [comment] 2021-02-09 06:57
if it do not work. I will try to switch from supplier to runtimeValue....

**Comment by ambition-consulting** [comment] 2021-02-11 10:05
### Logs
`10:45:59 INFO  traceId=, parentId=, spanId=, sampled= [io.qu.de.de.RuntimeUpdatesProcessor] (vert.x-worker-thread-1) Application restart not required, replacing classes via instrumentation
10:45:59 ERROR traceId=, parentId=, spanId=, sampled= [io.qu.de.de.RuntimeUpdatesProcessor] (vert.x-worker-thread-1) Failed to replace classes via instrumentation: java.lang.UnsupportedOperationException: class redefinition failed: attempted to delete a method
	at java.instrument/sun.instrument.InstrumentationImpl.redefineClasses0(Native Method)
	at java.instrument/sun.instrument.InstrumentationImpl.redefineClasses(InstrumentationImpl.java:193)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:219)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$2.handle(VertxHttpHotReplacementSetup.java:62)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$2.handle(VertxHttpHotReplacementSetup.java:52)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)`

...

`10:46:00 INFO  traceId=, parentId=, spanId=, sampled= [or.ap.cx.ws.se.fa.ReflectionServiceFactoryBean] (build-22) Creating Service {http://www.xxx from class xxx
10:46:00 FINE  traceId=, parentId=, spanId=, sampled= [ja.xm.bind] (build-22) Searching jaxb.properties
10:46:00 FINE  traceId=, parentId=, spanId=, sampled= [ja.xm.bind] (build-22) Checking system property javax.xml.bind.JAXBContextFactory
10:46:00 FINE  traceId=, parentId=, spanId=, sampled= [ja.xm.bind] (build-22)   not found
10:46:00 FINE  traceId=, parentId=, spanId=, sampled= [ja.xm.bind] (build-22) Checking system property javax.xml.bind.context.factory
10:46:00 FINE  traceId=, parentId=, spanId=, sampled= [ja.xm.bind] (build-22)   not found
10:46:00 FINE  traceId=, parentId=, spanId=, sampled= [ja.xm.bind] (build-22) Checking system property javax.xml.bind.JAXBContext
10:46:00 FINE  traceId=, parentId=, spanId=, sampled= [ja.xm.bind] (build-22)   not found
10:46:00 FINE  traceId=, parentId=, spanId=, sampled= [ja.xm.bind] (build-22) ServiceProvider loading Facility used; returning object [com.sun.xml.bind.v2.JAXBContextFactory]`

then multiple times:
`0:46:01 ERROR traceId=, parentId=, spanId=, sampled= [io.qu.de.de.IsolatedDevModeMain] (vert.x-worker-thread-1) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: Found 11 deployment problems: 
[1] Unsatisfied dependency for type java.lang.String and qualifiers [@Default]
	- java member: io.quarkiverse.cxf.CXFClientInfo#<init>()
	- declared on CLASS bean [types=[io.quarkiverse.cxf.CXFClientInfo, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkiverse.cxf.CXFClientInfo]
	The following beans match by type, but none have matching qualifiers:
		- Bean [class=java.lang.String, qualifiers=[@ConfigProperty, @Any]]
[2] Unsatisfied dependency for type java.lang.String and qualifiers [@Default]
	- java member: io.quarkiverse.cxf.CXFClientInfo#<init>()
	- declared on CLASS bean [types=[io.quarkiverse.cxf.CXFClientInfo, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkiverse.cxf.CXFClientInfo]
	The following beans match by type, but none have matching qualifiers:
		- Bean [class=java.lang.String, qualifiers=[@ConfigProperty, @Any]]
[3] Unsatisfied dependency for type java.lang.String and qualifiers [@Default]
	- java member: io.quarkiverse.cxf.CXFClientInfo#<init>()
	- declared on CLASS bean [types=[io.quarkiverse.cxf.CXFClientInfo, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkiverse.cxf.CXFClientInfo]
	The following beans match by type, but none have matching qualifiers:
		- Bean [class=java.lang.String, qualifiers=[@ConfigProperty, @Any]]
[4] Unsatisfied dependency for type java.lang.String and qualifiers [@Default]
	- java member: io.quarkiverse.cxf.CXFClientInfo#<init>()
	- declared on CLASS bean [types=[io.quarkiverse.cxf.CXFClientInfo, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkiverse.cxf.CXFClientInfo]
	The following beans match by type, but none have matching qualifiers:
		- Bean [class=java.lang.String, qualifiers=[@ConfigProperty, @Any]]
[5] Unsatisfied dependency for type java.lang.String and qualifiers [@Default]
	- java member: io.quarkiverse.cxf.CXFClientInfo#<init>()
	- declared on CLASS bean [types=[io.quarkiverse.cxf.CXFClientInfo, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkiverse.cxf.CXFClientInfo]
	The following beans match by type, but none have matching qualifiers:
		- Bean [class=java.lang.String, qualifiers=[@ConfigProperty, @Any]]
[6] Unsatisfied dependency for type java.lang.String and qualifiers [@Default]
	- java member: io.quarkiverse.cxf.CXFClientInfo#<init>()
	- declared on CLASS bean [types=[io.quarkiverse.cxf.CXFClientInfo, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkiverse.cxf.CXFClientInfo]
	The following beans match by type, but none have matching qualifiers:
		- Bean [class=java.lang.String, qualifiers=[@ConfigProperty, @Any]]
[7] Unsatisfied dependency for type java.lang.String and qualifiers [@Default]
	- java member: io.quarkiverse.cxf.CXFClientInfo#<init>()
	- declared on CLASS bean [types=[io.quarkiverse.cxf.CXFClientInfo, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkiverse.cxf.CXFClientInfo]
	The following beans match by type, but none have matching qualifiers:
		- Bean [class=java.lang.String, qualifiers=[@ConfigProperty, @Any]]
[8] Unsatisfied dependency for type java.lang.String and qualifiers [@Default]
	- java member: io.quarkiverse.cxf.CXFClientInfo#<init>()
	- declared on CLASS bean [types=[io.quarkiverse.cxf.CXFClientInfo, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkiverse.cxf.CXFClientInfo]
	The following beans match by type, but none have matching qualifiers:
		- Bean [class=java.lang.String, qualifiers=[@ConfigProperty, @Any]]
[9] Unsatisfied dependency for type java.lang.String and qualifiers [@Default]
	- java member: io.quarkiverse.cxf.CXFClientInfo#<init>()
	- declared on CLASS bean [types=[io.quarkiverse.cxf.CXFClientInfo, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkiverse.cxf.CXFClientInfo]
	The following beans match by type, but none have matching qualifiers:
		- Bean [class=java.lang.String, qualifiers=[@ConfigProperty, @Any]]
[10] Unsatisfied dependency for type java.lang.String and qualifiers [@Default]
	- java member: io.quarkiverse.cxf.CXFClientInfo#<init>()
	- declared on CLASS bean [types=[io.quarkiverse.cxf.CXFClientInfo, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkiverse.cxf.CXFClientInfo]
	The following beans match by type, but none have matching qualifiers:
		- Bean [class=java.lang.String, qualifiers=[@ConfigProperty, @Any]]
[11] Unsatisfied dependency for type java.util.List<java.lang.String> and qualifiers [@Default]
	- java member: io.quarkiverse.cxf.CXFClientInfo#<init>()
	- declared on CLASS bean [types=[io.quarkiverse.cxf.CXFClientInfo, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkiverse.cxf.CXFClientInfo]
	The following beans match by type, but none have matching qualifiers:
		- Bean [class=java.util.List, qualifiers=[@ConfigProperty, @Any]]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1072)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:245)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:129)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:423)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type java.lang.String and qualifiers [@Default]
	- java member: io.quarkiverse.cxf.CXFClientInfo#<init>()
	- declared on CLASS bean [types=[io.quarkiverse.cxf.CXFClientInfo, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkiverse.cxf.CXFClientInfo]
	The following beans match by type, but none have matching qualifiers:
		- Bean [class=java.lang.String, qualifiers=[@ConfigProperty, @Any]]
		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:484)
		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:378)
		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:237)
		... 12 more
	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type java.lang.String and qualifiers [@Default]
	- java member: io.quarkiverse.cxf.CXFClientInfo#<init>()
	- declared on CLASS bean [types=[io.quarkiverse.cxf.CXFClientInfo, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkiverse.cxf.CXFClientInfo]
	The following beans match by type, but none have matching qualifiers:
		- Bean [class=java.lang.String, qualifiers=[@ConfigProperty, @Any]]
		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:484)
		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:378)
		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:237)
		... 12 more
	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type java.lang.String and qualifiers [@Default]
	- java member: io.quarkiverse.cxf.CXFClientInfo#<init>()
	- declared on CLASS bean [types=[io.quarkiverse.cxf.CXFClientInfo, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkiverse.cxf.CXFClientInfo]
	The following beans match by type, but none have matching qualifiers:
		- Bean [class=java.lang.String, qualifiers=[@ConfigProperty, @Any]]
		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:484)
		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:378)
		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:237)
		... 12 more
	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type java.lang.String and qualifiers [@Default]
	- java member: io.quarkiverse.cxf.CXFClientInfo#<init>()
	- declared on CLASS bean [types=[io.quarkiverse.cxf.CXFClientInfo, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkiverse.cxf.CXFClientInfo]
	The following beans match by type, but none have matching qualifiers:
		- Bean [class=java.lang.String, qualifiers=[@ConfigProperty, @Any]]
		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:484)
		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:378)
		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:237)
		... 12 more
	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type java.lang.String and qualifiers [@Default]
	- java member: io.quarkiverse.cxf.CXFClientInfo#<init>()
	- declared on CLASS bean [types=[io.quarkiverse.cxf.CXFClientInfo, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkiverse.cxf.CXFClientInfo]
	The following beans match by type, but none have matching qualifiers:
		- Bean [class=java.lang.String, qualifiers=[@ConfigProperty, @Any]]
		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:484)
		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:378)
		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:237)
		... 12 more
	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type java.lang.String and qualifiers [@Default]
	- java member: io.quarkiverse.cxf.CXFClientInfo#<init>()
	- declared on CLASS bean [types=[io.quarkiverse.cxf.CXFClientInfo, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkiverse.cxf.CXFClientInfo]
	The following beans match by type, but none have matching qualifiers:
		- Bean [class=java.lang.String, qualifiers=[@ConfigProperty, @Any]]
		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:484)
		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:378)
		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:237)
		... 12 more
	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type java.lang.String and qualifiers [@Default]
	- java member: io.quarkiverse.cxf.CXFClientInfo#<init>()
	- declared on CLASS bean [types=[io.quarkiverse.cxf.CXFClientInfo, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkiverse.cxf.CXFClientInfo]
	The following beans match by type, but none have matching qualifiers:
		- Bean [class=java.lang.String, qualifiers=[@ConfigProperty, @Any]]
		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:484)
		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:378)
		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:237)
		... 12 more
	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type java.lang.String and qualifiers [@Default]
	- java member: io.quarkiverse.cxf.CXFClientInfo#<init>()
	- declared on CLASS bean [types=[io.quarkiverse.cxf.CXFClientInfo, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkiverse.cxf.CXFClientInfo]
	The following beans match by type, but none have matching qualifiers:
		- Bean [class=java.lang.String, qualifiers=[@ConfigProperty, @Any]]
		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:484)
		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:378)
		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:237)
		... 12 more
	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type java.lang.String and qualifiers [@Default]
	- java member: io.quarkiverse.cxf.CXFClientInfo#<init>()
	- declared on CLASS bean [types=[io.quarkiverse.cxf.CXFClientInfo, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkiverse.cxf.CXFClientInfo]
	The following beans match by type, but none have matching qualifiers:
		- Bean [class=java.lang.String, qualifiers=[@ConfigProperty, @Any]]
		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:484)
		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:378)
		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:237)
		... 12 more
	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type java.lang.String and qualifiers [@Default]
	- java member: io.quarkiverse.cxf.CXFClientInfo#<init>()
	- declared on CLASS bean [types=[io.quarkiverse.cxf.CXFClientInfo, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkiverse.cxf.CXFClientInfo]
	The following beans match by type, but none have matching qualifiers:
		- Bean [class=java.lang.String, qualifiers=[@ConfigProperty, @Any]]
		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:484)
		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:378)
		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:237)
		... 12 more
	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type java.util.List<java.lang.String> and qualifiers [@Default]
	- java member: io.quarkiverse.cxf.CXFClientInfo#<init>()
	- declared on CLASS bean [types=[io.quarkiverse.cxf.CXFClientInfo, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkiverse.cxf.CXFClientInfo]
	The following beans match by type, but none have matching qualifiers:
		- Bean [class=java.util.List, qualifiers=[@ConfigProperty, @Any]]
		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:484)
		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:378)
		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:237)
		... 12 more

	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:308)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.reloadExistingApplication(AugmentActionImpl.java:195)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.reloadExistingApplication(AugmentActionImpl.java:59)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.restartApp(IsolatedDevModeMain.java:188)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.restartCallback(IsolatedDevModeMain.java:174)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:237)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$2.handle(VertxHttpHotReplacementSetup.java:62)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$2.handle(VertxHttpHotReplacementSetup.java:52)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by ambition-consulting** [comment] 2021-02-11 10:18
@dufoli Well done! Can we get this merged for the next release please? It's quite annoying having to restart all the time.

**Closed** 2021-02-11 16:03 UTC
