### ISSUE TITLE
NTLM authentication

### ISSUE THREAD

**Issue by vtdmitriy** [quarkiverse/quarkus-cxf#273] opened 2021-07-26 12:56 UTC
Do you plan to support NTLM authentication on the client?

**Comment by dufoli** [comment] 2021-07-26 15:17
what do you mean by supporting ? 
all cxf function is available and you can use configurer method to configure the bus. I have not try but something like this : 
   ```
 void onStart(@Observes StartupEvent ev) {
        
        HTTPConduitConfigurer httpConduitConfigurer = new HTTPConduitConfigurer() {
            public void configure(String name, String address, HTTPConduit c) {
                AsyncHTTPConduit conduit = (AsyncHTTPConduit)c;
                DefaultHttpAsyncClient defaultHttpAsyncClient;
                defaultHttpAsyncClient = conduit.getHttpAsyncClient();
                defaultHttpAsyncClient.getCredentialsProvider().setCredentials( AuthScope.ANY,
                 new NTCredentials( USER,PWD, "", DOM ) );
                conduit.getClient().setAllowChunking( false );
                conduit.getClient().setAutoRedirect( true );
            }
        };

        final Bus bus = BusFactory.getThreadDefaultBus();
        bus.setExtension(httpConduitConfigurer, HTTPConduitConfigurer.class);
    }
```
prerequisit it to add the dependency : cxf-rt-transports-http-hc-x.x.x.jar

**Comment by vtdmitriy** [comment] 2021-07-28 11:39
There is no way to check yet, looks like a solution. I'm closing issue for now. 
Thanks.

**Comment by vtdmitriy** [comment] 2021-07-28 11:40
There is no way to check yet, looks like a solution. I'm closing issue for now. Thanks.

**Comment by vtdmitriy** [comment] 2021-09-10 12:40
I tried the proposed method in practice, but there were problems..
When using the latest versions of cxf-rt-transports-http-hc (for example 3.4.4, which is used in the current version of quarkus-cxf), the conduit.getHttpAsyncClient () method returns CloseableHttpAsyncClient, and the DefaultHttpAsyncClient class is deprecated.
Is there a way to set attributes for NTLM authentication in this case? I have not found ways without using reflection.

**Comment by shumonsharif** [comment] 2021-09-13 15:28
@vtdmitriy I have no good way of testing anything I suggest, but based on the [CXF docs here](https://cxf.apache.org/docs/asynchronous-client-http-transport.html), something like the below may possibly work for you?

```java
	@Inject @CXFClient
	HelloEndpoint helloEndpoint;

	@PostConstruct
	void configureNTCredentials() {
		if (helloEndpoint instanceof BindingProvider) {
			final var requestContext = ((BindingProvider) helloEndpoint).getRequestContext();
			/* request context should be threadsafe, see
			 * http://cxf.apache.org/faq.html#FAQ-AreJAX-WSclientproxiesthreadsafe?
			 */
			requestContext.put("thread.local.request.context", Boolean.TRUE);
			requestContext.put("use.async.http.conduit", Boolean.TRUE);
			Credentials creds = new NTCredentials("username", "pswd", null, "domain");
			requestContext.put(Credentials.class.getName(), creds);
		}
	}
```

**Comment by vtdmitriy** [comment] 2021-09-14 06:52
> @vtdmitriy I have no good way of testing anything I suggest, but based on the [CXF docs here](https://cxf.apache.org/docs/asynchronous-client-http-transport.html), something like the below may possibly work for you?
> 
Tried the above code, it results in an error: java.io.IOException: Authorization loop detected on Conduit" ... "on URL" ... "with realm" null ".
But what is most interesting, I found NTLM authentication works out of the box, when setting the login password through the properties
quarkus.cxf.client.test-client.username = test
quarkus.cxf.client.test-client.password = test

**Comment by shumonsharif** [comment] 2021-09-14 10:19
Based on the CXF source code for where this exception is thrown: https://github.com/apache/cxf/blob/cxf-3.4.4/rt/transports/http/src/main/java/org/apache/cxf/transport/http/HTTPConduit.java#L1939

        // If we have been here (URL & Realm) before for this particular message
        // retransmit, it means we have already supplied information
        // which must have been wrong, or we wouldn't be here again.
        // Otherwise, the server may be 401 looping us around the realms.

... which leads me to believe you may have some sort of configuration issue (either at the client or server).  The properties you used only configure basic authentication, which is an even bigger indication of a configuration issue.

**Comment by shumonsharif** [comment] 2021-10-16 12:05
Hi @vtdmitriy - I am closing this issue, given you have a workaround that seems to address the NTLM authentication, and both @dufoli and I have suggested some alternative ways as well.  Please feel free to reopen it if needed!

**Closed by shumonsharif** 2021-10-16 12:05 UTC

**Comment by raafael** [comment] 2023-03-06 20:05
Hi!

@shumonsharif  Unfortunelly for me the sample code it's not working. It's throwing this error:

Caused by: java.io.IOException: Authorization loop detected on Conduit

Setting login password through the properties like @vtdmitriy point out it's not working too

The version of quarkus-cxf that I'm using:  1.7.3

@shumonsharif May I missed some configuration to your sample code work?

**Comment by shumonsharif** [comment] 2023-03-06 21:04
Hi @raafael I unfortunately know very little about NTLM, and have no way of testing NTLM as I don't own a Windows machine.  Your best bet is to try NTML authentication with plain CXF (without Quarkus) - and let us know if the same code breaks with quarkus-cxf.

**Comment by vtdmitriy** [comment] 2023-03-07 12:28
In my case, as a result, @shumonsharif's code worked (using quarkiverse.cxf.version 0.13.1), the error occurred due to the fact that the username was incorrectly specified (specified with the domain). The properties option worked only because the external service also supports basic authorization.

**Comment by shumonsharif** [comment] 2023-03-07 21:34
Thanks for your helpful suggestions @vtdmitriy !!

**Comment by ppalaga** [comment] 2023-03-09 12:04
A test runnable on a GitHub Actions Windows worker node would be welcome!

**Comment by PureSpider** [comment] 2025-01-29 11:21
Sadly, neither suggestion works for me.

In my case, the WSDL is also secured via NTLM, so `@PostConstruct` is too late to set authentication data.
Also, like multiple people have said, the startup observer doesn't work (anymore) either since it's assuming an older version of the async HTTP client.

Does anyone have any pointers for me on how to set NTLM credentials in the startup observer so I can retrieve the WSDL needed to build the client?
