### ISSUE TITLE
userPrincipal is null in WebserviceContext

### ISSUE THREAD

**Issue by neXus1987** [quarkiverse/quarkus-cxf#92] opened 2021-01-07 09:34 UTC
Hi,

after upgrading from 0.2 to 0.3 the following principle is null:

 	@Resource
	WebServiceContext context;
....
_logger.error("auth: " + context.getUserPrincipal());

log:
auth: null

the IndentityProvider will have a principle, maybe this is regarding the update to vert.x?

Thanks
Phil

**Comment by dufoli** [comment] 2021-01-08 12:37
Do you use  resource in a webservice class. Maybe it is because it is not a bean....
I do not understand how it interact with webservice ??? Can you give more context code to reproduce...

**Comment by neXus1987** [comment] 2021-01-08 13:07
OK:
Interface:
```
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

@WebService(name = "Test")
public interface Test {

	@WebMethod
	@WebResult
	public String test(@WebParam(name = "val") String val);

}
```
Implementation:
```
import javax.annotation.Resource;
import javax.xml.ws.BindingType;
import javax.xml.ws.WebServiceContext;
import javax.xml.ws.soap.SOAPBinding;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@BindingType(value = SOAPBinding.SOAP12HTTP_BINDING)
public class TestEndpoint implements Test {
	@Resource
	WebServiceContext context;
	private static final Logger _logger = LoggerFactory.getLogger(TestEndpoint.class);

	@Override
	public String test(String val) {


		_logger.info("test:" + context.getUserPrincipal());
		return val;
	}

}
```
and with Version 0.2 the userPrinciple was filled and with version 0.3 it is null. The indentityProvider logic will be executed and fills also the userprinciple, but i guess that it were 2 different WebServiceContext.

**Comment by dufoli** [comment] 2021-01-11 08:11
it must has been fixed by commit of #52 can you test again ?

**Comment by neXus1987** [comment] 2021-01-11 09:45
With the current version of 0.4.0-SNAPSHOT the injected Bean is null (had added a new service Bean for testing) and the principle is also still null, the context object is not null (as with 0.3):

Endpoint:
```
import javax.annotation.Resource;
import javax.inject.Inject;
import javax.xml.ws.BindingType;
import javax.xml.ws.WebServiceContext;
import javax.xml.ws.soap.SOAPBinding;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import de.hellwach.service.HWMsvV1;

@BindingType(value = SOAPBinding.SOAP12HTTP_BINDING)
public class TestEndpoint implements Test {
	@Resource
	WebServiceContext context;
	private static final Logger _logger = LoggerFactory.getLogger(TestEndpoint.class);

	@Inject
	HWMsvV1 hwMsv;

	@Override
	public String test(String val) {

		_logger.info("context:" + context);
		_logger.info("userPrinciple:" + context.getUserPrincipal());
		_logger.info("hwMsv:" + hwMsv);

		return val;
	}

}
```

Interface:
```
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

@WebService(name = "Test")
public interface Test {

	@WebMethod
	@WebResult
	public String test(@WebParam(name = "val") String val);

}
```

Log:
```
2021-01-11 10:44:54,435 INFO  [de.hel.msv.TestEndpoint] (vert.x-worker-thread-1) context:org.apache.cxf.jaxws.context.WebServiceContextImpl@75bf4305
2021-01-11 10:44:54,436 INFO  [de.hel.msv.TestEndpoint] (vert.x-worker-thread-1) userPrinciple:null
2021-01-11 10:44:54,437 INFO  [de.hel.msv.TestEndpoint] (vert.x-worker-thread-1) hwMsv:null
```

**Comment by dufoli** [comment] 2021-01-15 11:47
@neXus1987 I found the issue and add a unit test on master. Can you test it again ? if it is ok, I think I will release again because many fixes has been done on current version.

**Comment by neXus1987** [comment] 2021-01-15 11:58
OK @Inject for the Service works now! But still the following Object seems to be the wrong instance of the class:
	```
@Resource
	WebServiceContext context;
```
because context is not null, but the principle object within the WebServiceContext is null.. and in Version 0.2 the principle Object was filled with the logged in user. And the IdentityProvider will still fill the userPrinciple.

**Comment by neXus1987** [comment] 2021-01-15 18:08
I tried also to inject the SecurityIdentity/SecurityContext direct but this won´t work. i need a way to get the loggedIn user, this is the main question (so it is not neccessary to get it via WebServiceContext).

**Comment by dufoli** [comment] 2021-01-15 20:38
Hmm I think I have to implement HttpServletRequest.getUserPrincipal() in the vertw http request

**Comment by dufoli** [comment] 2021-01-16 18:14
I have implement it but context.user() return null with vertx routingContext.
I try to add embeded auth handler but do not work.
I have to check why with quarkus team.
Because it seems strange...

**Comment by neXus1987** [comment] 2021-02-10 08:20
Any Updates on this issue or something i could do?

**Comment by dufoli** [comment] 2021-02-10 11:07
Nope, no time to work on it. You can ask to quarkus team on zulip or github issue to help because I do not know.

**Comment by dufoli** [comment] 2021-02-11 20:19
hmm I guess indeed that this is the same work, I have to do to support rolesAllowed annotation. I have  start to analyse and I will work on it when I found time.

**Comment by shumonsharif** [comment] 2021-02-20 17:47
Hey @dufoli @neXus1987 I was able to get this working.  If you are okay with it, I am going to submit a PR shortly, though I'm not sure how it may impact the `@RolesAllowed` implementation, as I haven't dug in there yet.

This PR will basically allow you to inject the SecurityIdentity as shown below.  I have only tested it so far with [basic auth](https://quarkus.io/guides/security-built-in-authentication#basic-auth) and the [properties driven security](https://quarkus.io/guides/security-properties) but I imagine it should work with other Quarkus security implementations too.

```java
import io.quarkus.security.identity.SecurityIdentity;
import org.jboss.logging.Logger;

import javax.inject.Inject;
import javax.xml.ws.BindingType;
import javax.xml.ws.soap.SOAPBinding;

@BindingType(value = SOAPBinding.SOAP12HTTP_BINDING)
public class TestEndpoint implements Test {

    private static final Logger logger = Logger.getLogger(TestEndpoint.class);

    @Inject
    SecurityIdentity si;

    @Override
    public String test(String val) {
        logger.info("SI:" + si);
        logger.info("userPrincipal:" + si.getPrincipal().getName());
        return val;
    }

}
```

**Closed** 2021-02-21 08:38 UTC
