### ISSUE TITLE
Wrap `java2ws` in Quarkus build time tooling

### ISSUE THREAD

**Issue by ppalaga** [quarkiverse/quarkus-cxf#797] opened 2023-04-04 11:41 UTC
Initially, generating WSDL out of Java would be enough. 

We already support `wsdl2java` via [Wsdl2JavaCodeGen](https://github.com/quarkiverse/quarkus-cxf/blob/75698ee1afbd6fb350b1aa3a9e0e2e54540d5d86/extensions/core/deployment/src/main/java/io/quarkiverse/cxf/deployment/codegen/Wsdl2JavaCodeGen.java) `java2ws` should work in the same way. We need to add some config and a new CodeGen class wrapping `java2ws`.

**Comment by JiriOndrusek** [comment] 2023-04-04 11:57
hi @ppalaga , may I be assigned to this issue? I'd like to fix it.

**Comment by ppalaga** [comment] 2023-04-04 13:10
Thanks, done, @JiriOndrusek

**Comment by JiriOndrusek** [comment] 2023-04-04 14:52
@ppalaga I've spent some time investigation this issue and I feel that it is not possible (or at least beneficial for users). Let me explain:

- `java2ws` requires compiled java class to be able to generate *.wsdl from it
- my understanding of `quarkus-maven-plugin` is that it is called in `generate-code` of the maven lifecycle, therefore it doesn't have acceess to compiled classes
- if this functionality was happening after the compilation, what would be beneficial opposed of using `cxf-java2ws-plugin`?

I probably miss some relation to make it sense for me.

Does my concern make sense to you? From the doc of the `CodeGenProvider`

```
Service providers for this interface are triggered during generate-sources phase of build of Quarkus applications
```

**Comment by JiriOndrusek** [comment] 2023-04-11 11:26
Hi @ppalaga 
I'm facing 2 issues. 
• My initial idea was to use `CombinedIndexBuildItem` to find all instances of `@WebService`, filter them  with includes and excludes (using regexPattern). Once I add `CombinedIndexBuildItem` as an input parameter of my build step, I'm getting a Quarkus exception `The build step is not currently running` (during execution)
• If I run the `java2ws` tool multiple times, I'm getting the same issue (`The build step is not currently running`)

In case that combinedIndexBuildItem is not present in my build step and there is only 1 execution of `java2ws` tool, the execution is successful and wsdl is generated.

Do you have an idea, what could be wrong with my idea?

**Comment by ppalaga** [comment] 2023-04-11 12:22
Could you please share your code?

**Comment by JiriOndrusek** [comment] 2023-04-11 12:42
Sure.
Here is my branch https://github.com/JiriOndrusek/quarkus-cxf/tree/797-java2wsdl-works-once

Older commit - https://github.com/JiriOndrusek/quarkus-cxf/commit/08ce5ac63a8cf924efdefd77a96fd6b12cdc9f56 - uses combined item to gain list of services. Fails
The newer commit - https://github.com/JiriOndrusek/quarkus-cxf/commit/cb6430d074f01c7ac363b017cc497e3a8e30309c - removes combined index and hardcodes the service class name and the transformation works.

Both cases could be executed via test `WsdlGenTest`.

(It is also possible to add use web service `FruitWebService` instead of `GreeterService`. But if both are generated at the same time, the process fails)

**Comment by JiriOndrusek** [comment] 2023-04-11 13:36
I see several compilation errors on my branch. (I was running the test via IDE), I'll add a fixing commit to it.

**Comment by JiriOndrusek** [comment] 2023-04-11 14:41
@ppalaga I found that the problem is happening here: [QuarkusCxfProcessor.QuarkusCapture](https://github.com/JiriOndrusek/quarkus-cxf/blob/main/extensions/core/deployment/src/main/java/io/quarkiverse/cxf/deployment/QuarkusCxfProcessor.java#L590)
I retested the scenario with the current 'main', because there were some changes near that line, but it still fails. I rebased my PR to `main`.

**Comment by JiriOndrusek** [comment] 2023-04-11 15:13
Does it make sense to you to pause generation in the code (from the comment above) during the execution of java2ws tool? (if it is possible)

**Closed** 2023-04-16 17:56 UTC
