### ISSUE TITLE
RoutingContext request do not provides X-Forwarded-Prefix header

### ISSUE THREAD

**Issue by demeureg** [quarkiverse/quarkus-cxf#1501] opened 2024-09-11 08:35 UTC
Originally reported as https://github.com/quarkusio/quarkus/issues/43183

### Describe the bug
Hello,

as we use quarkus-cxf for our SOAP webservice, header `X-Forwarded-Prefix` is not provided by [CxfHandler](https://github.com/quarkiverse/quarkus-cxf/blob/main/extensions/core/runtime/src/main/java/io/quarkiverse/cxf/transport/CxfHandler.java).

Regards,

Guillaume Demeure

### Expected behavior
If `X-Forwarded-Prefix` header is present, it should be provided to the handler and replace the context path.

### Actual behavior
Header `X-Forwarded-Prefix` is always null.

### How to Reproduce?
1. Start the application running SOAP service
2. From terminal, run:
   `curl -H 'X-Forwarded-Port: 443' -H 'X-Forwarded-Host: bla' 'X-Forwarded-Prefix: /proxy' -H 'X-Forwarded-Proto: https' 'http://localhost:8080/services/wifi?wsdl'`
3. At the bottom of your terminal, you should see:

```
...
  <wsdl:service name="WifiWSImpl">
    <wsdl:port binding="tns:WifiWSImplSoapBinding" name="WifiWSPort">
      <soap:address location="https://bla:443/services/wifi"/>
    </wsdl:port>
  </wsdl:service>
...
```

4. From a debug step into the [CxfHandler](https://github.com/quarkiverse/quarkus-cxf/blob/628fcf90ba0f212e3a46f3ad60a5626a19bac6ac/extensions/core/runtime/src/main/java/io/quarkiverse/cxf/transport/CxfHandler.java#L206), the list of headers names do not contains `X-Forwarded-Prefix`:

<img alt="image" width="423" src="https://private-user-images.githubusercontent.com/4477956/366366561-a4760ce8-f761-4465-9527-d6680e3cfdae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNjUxODUsIm5iZiI6MTcyNjE2NDg4NSwicGF0aCI6Ii80NDc3OTU2LzM2NjM2NjU2MS1hNDc2MGNlOC1mNzYxLTQ0NjUtOTUyNy1kNjY4MGUzY2ZkYWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTJUMTgxNDQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGJiNWVmZjMyYmYwZmQ2MWFjNDBjNDg4MGUxNDc1ZTMzODJiM2MyOWRmNDRhNDc5MDk2OTlmMjIyODQ5MmFlMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Vxkg1tKurXUn0IIXv5vpYh7iCGJQ8Y6bnq9BRGy7O2I">
### Output of `uname -a` or `ver`
Darwin mbp-de-gdemeure.home 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6030 arm64

### Output of `java -version`
openjdk version "21.0.2" 2024-01-16 OpenJDK Runtime Environment GraalVM CE 21.0.2+13.1 (build 21.0.2+13-jvmci-23.1-b30) OpenJDK 64-Bit Server VM GraalVM CE 21.0.2+13.1 (build 21.0.2+13-jvmci-23.1-b30, mixed mode, sharing)

### Quarkus version or git rev
3.8.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.9.5 (57804ffe001d7215b5e7bcb531cf83df38f93546) Maven home: /Users/g.demeure/.m2/wrapper/dists/apache-maven-3.9.5/2021cb71 Java version: 21.0.2, vendor: GraalVM Community, runtime: /Users/g.demeure/.sdkman/candidates/java/21.0.2-graalce Default locale: fr_FR, platform encoding: UTF-8 OS name: "mac os x", version: "14.6.1", arch: "aarch64", family: "mac"

**Comment by ppalaga** [comment] 2024-09-13 07:39
The condition in `checkXForwardedHeaders()` method was wrong assigning `originalPrefix` to null when `httpConfiguration.proxy.enableForwardedPrefix` was true. When I fixed it to be the other way round I found that the underlying Vert.x Request class already handles the X-Forwarded headers itself and therefore the `checkXForwardedHeaders()` method is not needed at all. 

Anyway, the broken condition actually prevented the prefix to be added twice, so there was no observable misbehavior (as long as `quarkus.http.proxy.enable-forwarded-prefix = true` was set). That's why I did not mark the PR https://github.com/quarkiverse/quarkus-cxf/pull/1503 as fixing this issue and that's why I am closing this issue as not a bug.

**Closed** 2024-09-13 17:09 UTC
