### ISSUE TITLE
Take long time when building - cannot merge wsdl.plugin.xml

### ISSUE THREAD

**Issue by AlstonTsaoTSMC** [quarkiverse/quarkus-cxf#744] opened 2023-03-02 10:41 UTC
HI,

I'm using quarkus-cxf, one day it become so slow when building (both quarkus:dev or mvn package). As shown below, it takes 2 minutes to merge wsdl.plugin.xml and I don't know how to disable it. I'm using quarkus 3.0.0.Alpha + JDK 17 + quarkus-cxf 2.0.0.Alpha. 
```
2023-03-02 18:30:50,581 INFO  [io.qua.cxf.dep.CxfEndpointImplementationProcessor] (build-9) Not registering a Vert.x handler for CXF as no WS endpoints were found at build time and no other extension requested it
2023-03-02 18:33:00,211 WARN  [io.qua.cxf.dep.QuarkusCxfProcessor] (build-18) cannot merge wsdl.plugin.xml
```

pom.xml
```xml
    <dependency>
      <groupId>io.quarkiverse.cxf</groupId>
      <artifactId>quarkus-cxf</artifactId>
      <version>2.0.0.Alpha1</version>
    </dependency>
    <dependency>
      <groupId>jakarta.xml.ws</groupId>
      <artifactId>jakarta.xml.ws-api</artifactId>
      <version>4.0.0</version>
    </dependency>
    <dependency>
      <groupId>io.quarkiverse.cxf</groupId>
      <artifactId>quarkus-cxf-rt-features-logging</artifactId>
      <version>2.0.0.Alpha1</version>
    </dependency>
```

**Comment by shumonsharif** [comment] 2023-03-02 12:25
Hi @AlstonTsaoTSMC Thanks for the issue.  Unfortunately I'm not able to recreate it.  

Which OS (and version) are you on, and can you try switching to the BOM as described [here](https://quarkiverse.github.io/quarkiverse-docs/quarkus-cxf/dev/user-guide/create-project.html#dependency-management)?  

Also, a few other points worth noting:

- You shouldn't be introducing the `jakarta.xml.ws:jakarta.xml.ws-api:4.0.0` dependency, quarkus-cxf will pull in the correct version.
- You didn't specify the exact versions for Quarkus and the extension, so I'm assuming you are using Quarkus 3.0.0.Alpha4 and quarkus-cxf 2.0.0.Alpha1?
- Please let us know the exact JDK version you are using as well, in case the above doesn't fix things.

**Comment by AlstonTsaoTSMC** [comment] 2023-03-03 01:53
I'm using
```
Ubuntu 20.04.5 LTS
Quarkus 3.0.0.Alpha4
Kotlin 1.8.10
Maven compiler release: 1.7
JDK: Eclipse Temurin 17

```


I did use the BOM:
```
<dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>${quarkus.platform.artifact-id}</artifactId>
        <version>${quarkus.platform.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
```

**Comment by shumonsharif** [comment] 2023-03-03 02:37
I was referring to the `quarkus-cxf-bom` as per the link I shared.  And I don't believe there are network calls for the merge.

**Comment by AlstonTsaoTSMC** [comment] 2023-03-03 07:41
> 

If so, is there anyway to disable the network calls?

**Comment by shumonsharif** [comment] 2023-03-03 12:44
> > EDIT: There may actually be some network calls happening ... will need to dig in further.
> 
> If so, is there anyway to disable the network calls?

Unfortunately, we'll need a code fix to address the root cause of this issue, I'm going to be submitting a PR shortly.

You may have some luck with the slowness issue by editing your `/etc/hosts` file and adding the following entry in it:
```
127.0.0.1 java.sun.com
```

While the above may help with the slowness, you'll essentially not be able to access java.sun.com sites, so be sure to revert once the next release is available.

**Comment by ppalaga** [comment] 2023-03-14 08:42
Closing in hope that this was fixed via https://github.com/quarkiverse/quarkus-cxf/pull/748
Please feel free to reopen otherwise.

**Closed by ppalaga** 2023-03-14 08:42 UTC
